Hw/task 5
BigWickedDaddy/Android2course pull request #5
Opened 2021-11-01 15:40 UTC by BigWickedDaddy

![photo_2021-11-01_18-38-34](https://user-images.githubuserco

https://user-images.githubusercontent.com/81323621/139698932-8732e99b-f018-4ad7-878f-915a93cda967.MOV

ntent.com/81323621/139698917-e873e639-05fe-4f34-9357-ba5dff30d3ea.jpg)
![photo_2021-11-01_18-38-33](https://user-images.githubusercontent.com/81323621/139698922-2e59a8c1-2053-4168-9ea8-6056d899680a.jpg)

2021-11-01 15:41 UTC, BigWickedDaddy commented
![photo_2021-11-01_18-38-34](https://user-images.githubusercontent.com/81323621/139699027-52949e1e-62dd-4738-b18c-9fa426859380.jpg)

2021-12-22 00:30 UTC, NailShaykhrazievItis commented on 1SemITIS/app/src/main/java/com/itis/a1semitis/PersonHolder.kt
> +) : RecyclerView.ViewHolder(item) {
мог сразу в конструктор передать ItemPersonBinding, потом вызвать ecyclerView.ViewHolder(binding.root)

2021-12-22 00:31 UTC, NailShaykhrazievItis requested changes

2021-12-22 00:31 UTC, NailShaykhrazievItis commented on 1SemITIS/app/src/main/java/com/itis/a1semitis/PersonHolder.kt
> +            val context = itemView.context
Холдер не знает ничего про активити, не его зона ответсвенности, он возвращает только коллбек

2022-03-05 06:30 UTC, closed without merging